import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://tpbackend.tpsmartsol.com/');
  await page.getByPlaceholder('Enter your email address').click();
  await page.getByPlaceholder('Enter your email address').fill('harsha@tparamount.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('password');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'HR harsha reddy' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByText('LocationsLocationLocation').click();
  await page.getByRole('link', { name: 'Users' }).click();
  await page.getByRole('button', { name: '+ User' }).click();
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('asdf');
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').fill('jkkk');
  await page.getByPlaceholder('Client Email').click();
  await page.getByPlaceholder('Client Email').fill('sdf@gmail.com');
  await page.getByPlaceholder('Client Email').press('Tab');
  await page.getByPlaceholder('Password').fill('password');
  await page.getByLabel('Filter').selectOption('SUPERADMIN');
  await page.getByPlaceholder('Phone').click();
  await page.getByLabel('Filter').selectOption('USER');
  await page.getByPlaceholder('Phone').click();
  await page.getByPlaceholder('Phone').fill('+91 90909-09090');
  await page.locator('#root svg').click();
  await page.getByRole('option', { name: 'GUJRAT' }).click();
  await page.locator('svg').nth(2).click();
  await page.getByRole('option', { name: 'KUKATPALLI' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});
